# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild]
steps:
  # This step runs the unit tests on the app
  - name: 'node:14-slim'
    id: Test
    entrypoint: /bin/sh
    args:
      - -c
      - |
        # Install dependencies
        npm install
        # Run the tests
        npm test

# This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/nodejs/nodejs-image:$SHORT_SHA'
    - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/nodejs/nodejs-image:$SHORT_SHA'

# This step deploys the new version of our container image
# in the hello-cloudbuild Kubernetes Engine cluster.

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Authenticate with the Kubernetes cluster
        gcloud container clusters get-credentials gkecluster --zone us-central1-a --project kubernetes2-410610

        # Install Helm
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

        # Run Helm command after installation
        helm upgrade --install node-app ./nodejs-application -n nodejs --create-namespace  --set image.tag=$SHORT_SHA